### ISSUE TITLE
Mattertags onClick Event

### ISSUE THREAD

**Issue by mingcnjs** [loic-meister-guild/pj-matterport-sdk-2021-tutorial#1]
Thanks for these work.
How can we use onClick Event of Mattertags?

**Comment by loic-meister-guild** [comment]
Try using [mpSdk.on(event, callback)](https://matterport.github.io/showcase-sdk/docs/sdk/reference/current/index.html#on) with the [mpSdk.Mattertag.Event.CLICK](https://matterport.github.io/showcase-sdk/docs/sdk/reference/current/enums/mattertag.event.html#click) event (which fires when the input pointer clicks a Mattertag disc), and a callback function with the following `(tagSid: string, url: string): void` signature.

Actually you can find such an example on the documentation page for the [mpSdk.on(event, callback)](https://matterport.github.io/showcase-sdk/docs/sdk/reference/current/index.html#on) method:

```JavaScript
mpSdk.on(mpSdk.Mattertag.Event.CLICK,
  function (tagSid) {
    console.log(tagSid + ' was selected');
  }
);
```

Does that answer you question?

**Comment by alex09j22** [comment]
Yes, exactly.
Thanks for your comment

**Comment by loic-meister-guild** [comment]
You're welcome

**Comment by alex09j22** [comment]
Can we disable hover event for mattertag?
Actually, when we hover mattertag, it is showing label element.

**Comment by alex09j22** [comment]
:+1:
