### ISSUE TITLE
How to fix CORS error?

### ISSUE THREAD

**Issue by alex09j22** [loic-meister-guild/pj-matterport-sdk-2021-tutorial#3]
When we iterate sdk with localhost, there was cos error.
For example, when we register Icon to mattertag like this, it returned cors error.
<code>
await mpSdk.Mattertag.registerIcon(
 "hotspot1",
 `/assets/icon.png`
);
</code>

#### error:
`Access to image at 'http://localhost:3000/assets/icon.png' from origin 'https://my.matterport.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

How can we fix this issue?

Thanks

**Comment by loic-meister-guild** [comment]
Check your call to `showcase.contentWindow.MP_SDK.connect()` did succeed, otherwise can you try with an image accessible from the internet, not on a local server.

**Comment by alex09j22** [comment]
:+1:
