### ISSUE TITLE
Is it possible to handling mattertag icon width and height?

### ISSUE THREAD

**Issue by alex09j22** [loic-meister-guild/pj-matterport-sdk-2021-tutorial#4]

**Comment by loic-meister-guild** [comment]
Apparently, the size depends on the size of the icon you set and in case it is a SVG file without width and height, it defaults to 128x128 as explain in the documentation for [@mpSdk / Mattertag / editIcon(tagSid: string, iconId: string): Promise<void>](https://matterport.github.io/showcase-sdk/docs/sdk/reference/current/modules/mattertag.html#editicon).

**Comment by alex09j22** [comment]
:+1:
